(ns bitecho.sieve.core-test
  "Tests for Sieve consistent broadcast validation."
  (:require [bitecho.basalt.core :as basalt]
            [bitecho.crypto :as crypto]
            [bitecho.sieve.core :as sieve]
            [clojure.test :refer [deftest is testing]]
            [clojure.test.check.clojure-test :refer [defspec]]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.properties :as prop]))

(def ^:private gen-bytes
  (gen/fmap byte-array (gen/vector gen/byte 1 1024)))

(defspec ^{:doc "Valid signatures generated by wrap-message should be accepted by validate-message."}
  valid-signature-accepted
  100
  (prop/for-all [payload gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      message (sieve/wrap-message payload (:private keypair) (:public keypair))
                      validated (sieve/validate-message message)]
                  (and (some? validated)
                       (= (seq payload) (seq (:payload validated)))
                       (= (basalt/bytes->hex (:public keypair)) (:sender validated))))))

(defspec ^{:doc "Invalid signatures should be dropped by validate-message."}
  invalid-signature-dropped
  100
  (prop/for-all [payload gen-bytes
                 fake-payload gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      message (sieve/wrap-message payload (:private keypair) (:public keypair))
          ;; Tamper with the payload
                      tampered-message (assoc message :payload fake-payload)]
                  (if (= (seq payload) (seq fake-payload))
                    true ;; If by chance the payloads are equal, the signature is valid
                    (nil? (sieve/validate-message tampered-message))))))

(deftest ^{:doc "Test explicit bad signature cases."}
  tampered-signature-test
  (testing "Tampered signature drops message"
    (let [payload (.getBytes "hello sieve" "UTF-8")
          keypair (crypto/generate-keypair)
          message (sieve/wrap-message payload (:private keypair) (:public keypair))
          tampered-sig (byte-array (map inc (:signature message)))
          tampered-message (assoc message :signature tampered-sig)]
      (is (nil? (sieve/validate-message tampered-message)))))

  (testing "Tampered public key drops message"
    (let [payload (.getBytes "hello sieve" "UTF-8")
          keypair (crypto/generate-keypair)
          message (sieve/wrap-message payload (:private keypair) (:public keypair))
          other-keypair (crypto/generate-keypair)
          tampered-message (assoc message :sender (basalt/bytes->hex (:public other-keypair)))]
      (is (nil? (sieve/validate-message tampered-message))))))

(defspec ^{:doc "First message from sender updates history."}
  check-equivocation-first-message
  100
  (prop/for-all [payload gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      message (sieve/wrap-message payload (:private keypair) (:public keypair))
                      empty-history {}
                      result (sieve/check-equivocation empty-history message)]
                  (and
                   (not (:equivocation? result))
                   (= (basalt/bytes->hex (:signature message))
                      (get (:history result) (:sender message)))))))

(defspec ^{:doc "Same signature is not an equivocation."}
  check-equivocation-duplicate-message
  100
  (prop/for-all [payload gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      message (sieve/wrap-message payload (:private keypair) (:public keypair))
                      history {(:sender message) (basalt/bytes->hex (:signature message))}
                      result (sieve/check-equivocation history message)]
                  (and
                   (not (:equivocation? result))
                   (= history (:history result))))))

(defspec ^{:doc "Different signature from the same sender is an equivocation."}
  check-equivocation-different-message
  100
  (prop/for-all [payload1 gen-bytes
                 payload2 gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      msg1 (sieve/wrap-message payload1 (:private keypair) (:public keypair))
                      msg2 (sieve/wrap-message payload2 (:private keypair) (:public keypair))
                      history {(:sender msg1) (basalt/bytes->hex (:signature msg1))}
                      result (sieve/check-equivocation history msg2)]
                  (if (= (seq payload1) (seq payload2))
                    true
                    (and
                     (:equivocation? result)
                     (= history (:history result)))))))
