(ns bitecho.sieve.core-test
  "Tests for Sieve consistent broadcast validation."
  (:require [bitecho.basalt.core :as basalt]
            [bitecho.crypto :as crypto]
            [bitecho.sieve.core :as sieve]
            [clojure.test :refer [deftest is testing]]
            [clojure.test.check.clojure-test :refer [defspec]]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.properties :as prop]))

(def ^:private gen-bytes
  (gen/fmap byte-array (gen/vector gen/byte 1 1024)))

(defspec ^{:doc "Valid signatures generated by wrap-message should be accepted by validate-message."}
  valid-signature-accepted
  100
  (prop/for-all [payload gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      message (sieve/wrap-message payload (:private keypair) (:public keypair))
                      validated (sieve/validate-message message)]
                  (and (some? validated)
                       (= (seq payload) (seq (:payload validated)))
                       (= (basalt/bytes->hex (:public keypair)) (:sender validated))))))

(defspec ^{:doc "Invalid signatures should be dropped by validate-message."}
  invalid-signature-dropped
  100
  (prop/for-all [payload gen-bytes
                 fake-payload gen-bytes]
                (let [keypair (crypto/generate-keypair)
                      message (sieve/wrap-message payload (:private keypair) (:public keypair))
          ;; Tamper with the payload
                      tampered-message (assoc message :payload fake-payload)]
                  (if (= (seq payload) (seq fake-payload))
                    true ;; If by chance the payloads are equal, the signature is valid
                    (nil? (sieve/validate-message tampered-message))))))

(deftest ^{:doc "Test explicit bad signature cases."}
  tampered-signature-test
  (testing "Tampered signature drops message"
    (let [payload (.getBytes "hello sieve" "UTF-8")
          keypair (crypto/generate-keypair)
          message (sieve/wrap-message payload (:private keypair) (:public keypair))
          tampered-sig (byte-array (map inc (:signature message)))
          tampered-message (assoc message :signature tampered-sig)]
      (is (nil? (sieve/validate-message tampered-message)))))

  (testing "Tampered public key drops message"
    (let [payload (.getBytes "hello sieve" "UTF-8")
          keypair (crypto/generate-keypair)
          message (sieve/wrap-message payload (:private keypair) (:public keypair))
          other-keypair (crypto/generate-keypair)
          tampered-message (assoc message :sender (basalt/bytes->hex (:public other-keypair)))]
      (is (nil? (sieve/validate-message tampered-message))))))
